package com.ptit.exam.ui.view.admin;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.ptit.exam.util.ImagePanel;

import javax.swing.*;
import java.awt.*;

/**
 * User: thuongntt
 * Date: 12/5/13
 * Time: 1:46 AM
 */
public class ExportExamGUI extends JPanel
{
    private JButton btnCancel;
    private JButton btnExport;
    private JPanel exportExamCard;
    private JPanel contentPanel;
    private JComboBox cbSubjectName;
    private JComboBox cbExamName;
    private JButton btnGenerateExam;
    private JTextArea txtContent;
    private JPanel searchPanel;

    public JButton getBtnCancel()
    {
        return btnCancel;
    }

    public JButton getBtnExport()
    {
        return btnExport;
    }

    public JComboBox getCbSubjectName()
    {
        return cbSubjectName;
    }

    public JComboBox getCbExamName()
    {
        return cbExamName;
    }

    public JButton getBtnGenerateExam()
    {
        return btnGenerateExam;
    }

    public JTextArea getTxtContent()
    {
        return txtContent;
    }

    public void resetExportExamGUI()
    {
        txtContent.setText("");
    }

    private void createUIComponents()
    {
        exportExamCard = new ImagePanel("background_sub_panel.jpg");
        searchPanel = new ImagePanel("background_sub_panel.jpg");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        createUIComponents();
        exportExamCard.setLayout(new GridLayoutManager(2, 7, new Insets(0, 0, 0, 0), -1, -1));
        exportExamCard.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLoweredBevelBorder(), null));
        final JScrollPane scrollPane1 = new JScrollPane();
        exportExamCard.add(scrollPane1, new GridConstraints(0, 0, 1, 7, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPane1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLoweredBevelBorder(), null));
        contentPanel = new JPanel();
        contentPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        scrollPane1.setViewportView(contentPanel);
        contentPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLoweredBevelBorder(), null));
        searchPanel.setLayout(new GridLayoutManager(1, 13, new Insets(0, 0, 0, 0), -1, -1));
        contentPanel.add(searchPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        searchPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        final JLabel label1 = new JLabel();
        label1.setText("Chọn Môn Thi");
        searchPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(76, 14), null, 0, false));
        cbSubjectName = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        cbSubjectName.setModel(defaultComboBoxModel1);
        searchPanel.add(cbSubjectName, new GridConstraints(0, 1, 1, 5, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Chọn Đề Thi");
        searchPanel.add(label2, new GridConstraints(0, 6, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cbExamName = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        cbExamName.setModel(defaultComboBoxModel2);
        searchPanel.add(cbExamName, new GridConstraints(0, 7, 1, 5, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnGenerateExam = new JButton();
        btnGenerateExam.setBorderPainted(false);
        btnGenerateExam.setContentAreaFilled(false);
        btnGenerateExam.setIcon(new ImageIcon(getClass().getResource("/images/btn_create_exam.png")));
        btnGenerateExam.setLabel("");
        btnGenerateExam.setMargin(new Insets(0, 0, 0, 0));
        btnGenerateExam.setText("");
        searchPanel.add(btnGenerateExam, new GridConstraints(0, 12, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane2 = new JScrollPane();
        contentPanel.add(scrollPane2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        txtContent = new JTextArea();
        scrollPane2.setViewportView(txtContent);
        btnExport = new JButton();
        btnExport.setBorderPainted(false);
        btnExport.setContentAreaFilled(false);
        btnExport.setIcon(new ImageIcon(getClass().getResource("/images/btn_export_exam.png")));
        btnExport.setInheritsPopupMenu(true);
        btnExport.setLabel("");
        btnExport.setMargin(new Insets(0, 0, 0, 0));
        btnExport.setText("");
        exportExamCard.add(btnExport, new GridConstraints(1, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        exportExamCard.add(spacer1, new GridConstraints(1, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, new Dimension(76, 11), null, 0, false));
        btnCancel = new JButton();
        btnCancel.setBorderPainted(false);
        btnCancel.setContentAreaFilled(false);
        btnCancel.setIcon(new ImageIcon(getClass().getResource("/images/btn_cancel.png")));
        btnCancel.setLabel("");
        btnCancel.setMargin(new Insets(0, 0, 0, 0));
        btnCancel.setText("");
        exportExamCard.add(btnCancel, new GridConstraints(1, 6, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return exportExamCard;
    }
}
