package com.ptit.exam.ui.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import com.ptit.exam.ui.control.LoginController;
import com.ptit.exam.util.GlobalValues;
import com.ptit.exam.util.ImagePanel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * User: thuongntt
 * Date: 9/22/13
 * Time: 1:58 PM
 */

@Component
public class LoginGUI extends JFrame {
    private JComboBox cbxBusiness;
    private JTextField txtUsername;
    private JPasswordField txtPassword;
    private JButton btnLogin;
    private JButton btnQuit;
    private JPanel loginPanel;
    private JPanel loginContent;

    @Autowired
    LoginController loginController;

    @Autowired
    ChangePasswordGUI changePasswordGUI;

    public LoginGUI() {
        $$$setupUI$$$();
        setContentPane(loginPanel);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xSize = (int) tk.getScreenSize().getWidth();
        int ySize = (int) tk.getScreenSize().getHeight() - 50;
        setSize(xSize, ySize);

        setUpActionListener();
    }

    private void setUpActionListener() {
        if (GlobalValues.LOGIN_ADD_ACTION) {
            btnLogin.addActionListener(actionListener);
            btnQuit.addActionListener(actionListener);
        }
        GlobalValues.LOGIN_ADD_ACTION = false;
    }

    private ActionListener actionListener = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == btnLogin) {
                loginController.doLogin();
            }
            if (e.getSource() == btnQuit) {
                loginController.doQuit();
            }
        }
    };

    public JTextField getTxtUsername() {
        return txtUsername;
    }

    public JPasswordField getTxtPassword() {
        return txtPassword;
    }

    public JComboBox getCbxBusiness() {
        return cbxBusiness;
    }

    private void createUIComponents() {
        loginPanel = new ImagePanel("background.jpg");
        pack();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        loginPanel.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:d:grow", "center:20px:grow,top:4dlu:noGrow,center:94px:noGrow,center:d:noGrow,top:4dlu:noGrow,center:d:grow"));
        loginPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-13421773)), null));
        loginContent = new JPanel();
        loginContent.setLayout(new GridLayoutManager(4, 3, new Insets(10, 10, 10, 10), -1, -1));
        loginContent.setInheritsPopupMenu(false);
        loginContent.setMaximumSize(new Dimension(-1, -1));
        loginContent.setMinimumSize(new Dimension(-1, -1));
        loginContent.setOpaque(true);
        loginContent.setPreferredSize(new Dimension(330, 200));
        loginContent.setRequestFocusEnabled(true);
        CellConstraints cc = new CellConstraints();
        loginPanel.add(loginContent, cc.xy(3, 4, CellConstraints.CENTER, CellConstraints.FILL));
        loginContent.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLoweredBevelBorder(), null));
        final JLabel label1 = new JLabel();
        label1.setText("Ch?c v? :");
        loginContent.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(30, 14), null, 0, false));
        cbxBusiness = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Admin");
        defaultComboBoxModel1.addElement("Student");
        cbxBusiness.setModel(defaultComboBoxModel1);
        loginContent.add(cbxBusiness, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(19, 24), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Tài kho?n :");
        loginContent.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(30, 14), null, 0, false));
        txtUsername = new JTextField();
        txtUsername.setMargin(new Insets(0, 0, 0, 0));
        txtUsername.setText("admin");
        loginContent.add(txtUsername, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 30), null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("M?t kh?u :");
        loginContent.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(30, 14), null, 0, false));
        txtPassword = new JPasswordField();
        txtPassword.setMargin(new Insets(0, 0, 0, 0));
        txtPassword.setText("admin");
        loginContent.add(txtPassword, new GridConstraints(2, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 30), null, 0, false));
        btnLogin = new JButton();
        btnLogin.setAutoscrolls(false);
        btnLogin.setBorderPainted(false);
        btnLogin.setContentAreaFilled(false);
        btnLogin.setDefaultCapable(true);
        btnLogin.setIcon(new ImageIcon(getClass().getResource("/images/btn_login.png")));
        btnLogin.setLabel("");
        btnLogin.setMargin(new Insets(0, 0, 0, 0));
        btnLogin.setText("");
        loginContent.add(btnLogin, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(100, 30), new Dimension(19, 30), new Dimension(100, 30), 0, false));
        btnQuit = new JButton();
        btnQuit.setBorderPainted(false);
        btnQuit.setContentAreaFilled(false);
        btnQuit.setDefaultCapable(false);
        btnQuit.setIcon(new ImageIcon(getClass().getResource("/images/btn_cancel.png")));
        btnQuit.setIconTextGap(1);
        btnQuit.setMargin(new Insets(0, 0, 0, 0));
        btnQuit.setText("");
        btnQuit.setVerifyInputWhenFocusTarget(true);
        loginContent.add(btnQuit, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(100, 30), new Dimension(18, 30), new Dimension(100, 30), 0, false));
        final Spacer spacer1 = new Spacer();
        loginPanel.add(spacer1, cc.xy(3, 1, CellConstraints.CENTER, CellConstraints.FILL));
        final Spacer spacer2 = new Spacer();
        loginPanel.add(spacer2, cc.xy(3, 6, CellConstraints.CENTER, CellConstraints.FILL));
        final Spacer spacer3 = new Spacer();
        loginPanel.add(spacer3, cc.xyw(1, 4, 2, CellConstraints.FILL, CellConstraints.DEFAULT));
        final Spacer spacer4 = new Spacer();
        loginPanel.add(spacer4, cc.xy(5, 4, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label4 = new JLabel();
        label4.setIcon(new ImageIcon(getClass().getResource("/images/login_text.png")));
        label4.setText("");
        loginPanel.add(label4, cc.xy(3, 3, CellConstraints.CENTER, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return loginPanel;
    }
}
